py: chunking works, arc-sample-generation works for 2d, socket samples, wait-all mode, pickle object to turn off pc, workers can start in burst mode

diff --git a/run-workers b/run-workers
--- a/run-workers
+++ b/run-workers
@@ -6,17 +6,43 @@ else
   cores=$(grep -c ^processor /proc/cpuinfo)-2
 fi
 
-
-
-declare -a workers;
-for ((core=1; core <= cores; core++))
-do
-  /home/franksyj/.local/bin/rq worker step_size_analysis drift_analysis --url redis://:4xEhjbGNkNPr8UkBQbWL9qmPpXpAeCKMF2G2@nash.ini.rub.de:6379 --path /home/franksyj/DriftAnalysisFramework/py/ &
-  workers[core]=$!;
-  echo "Started Core $core with process $!";
+burst = false
+while getopts ":n:b:" opt; do
+  case $opt in
+    n) niceness="$OPTARG"
+    ;;
+    b) burst=true
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
 done
 
-/home/franksyj/.local/bin/rq worker step_size_analysis drift_analysis --url redis://:4xEhjbGNkNPr8UkBQbWL9qmPpXpAeCKMF2G2@nash.ini.rub.de:6379 --path /home/franksyj/DriftAnalysisFramework/py/
+
+if [ "$burst" != false ]; then
+  echo "Burst Mode"
+  declare -a workers;
+  for ((core=1; core <= cores; core++))
+  do
+    /home/franksyj/.local/bin/rq worker --burst step_size_analysis drift_analysis --url redis://:4xEhjbGNkNPr8UkBQbWL9qmPpXpAeCKMF2G2@nash.ini.rub.de:6379 --path /home/franksyj/DriftAnalysisFramework/py/ &
+    workers[core]=$!;
+    echo "Started Core $core with process $!";
+  done
+
+  /home/franksyj/.local/bin/rq worker --burst step_size_analysis drift_analysis --url redis://:4xEhjbGNkNPr8UkBQbWL9qmPpXpAeCKMF2G2@nash.ini.rub.de:6379 --path /home/franksyj/DriftAnalysisFramework/py/
+
+else
+  declare -a workers;
+  for ((core=1; core <= cores; core++))
+  do
+    /home/franksyj/.local/bin/rq worker step_size_analysis drift_analysis --url redis://:4xEhjbGNkNPr8UkBQbWL9qmPpXpAeCKMF2G2@nash.ini.rub.de:6379 --path /home/franksyj/DriftAnalysisFramework/py/ &
+    workers[core]=$!;
+    echo "Started Core $core with process $!";
+  done
+
+  /home/franksyj/.local/bin/rq worker step_size_analysis drift_analysis --url redis://:4xEhjbGNkNPr8UkBQbWL9qmPpXpAeCKMF2G2@nash.ini.rub.de:6379 --path /home/franksyj/DriftAnalysisFramework/py/
+fi
+
 
 function kill_workers()
 {
